apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-frontend
  namespace: sentiment-app

spec:
  replicas: 3

  selector:
    matchLabels:
      app: sentiment-frontend

  template:
    metadata:
      labels:
        app: sentiment-frontend

    spec:
      nodeSelector:
        role: frontend

      containers:
        - name: sentiment-frontend
          image: 487620625686.dkr.ecr.eu-north-1.amazonaws.com/sentiment-frontend:12

          ports:
            - containerPort: 80

          env:
            - name: BACKEND_URL
              valueFrom:
                secretKeyRef:
                  name: frontend-secret
                  key: BACKEND_URL

      imagePullSecrets:
        - name: ecr-secret
